name: Build and tests

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Run tests
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov
    - name: Report coverage
      if: ${{ github.event_name == 'push' }}
      run: |
        ls -lh Textify.Tests
        curl -s https://codecov.io/bash > codecov
        chmod +x codecov
        ./codecov -f "Textify.Tests/coverage.info" -t ${{ secrets.CODECOV_TOKEN }}
